export enum ActionType {
  SET_FROM_LANGUAGE = 'SET_FROM_LANGUAGE',
  SET_TO_LANGUAGE = 'SET_TO_LANGUAGE',
  INTERCHANGE_LANGUAGE = 'CHANGE_LANGUAGE',
  SET_FROM_TEXT = 'SET_FROM_TEXT',
  SET_RESULT_TEXT = 'SET_RESULT_TEXT',
}
